### ISSUE TITLE
Question about knitting vs. running chunks ("Run All")

### ISSUE THREAD

**Issue by pat-s** [krlmlr/here#4]
When running all chunks of my .Rmd file ("Run All"), `here()` is set to the R-project root dir. All paths are relative to this directory. Let's call it "main-dir".

The .Rmd file is placed one dir below the project root, let's say in "main-dir/sub-dir". When I knit the .Rmd file, I get `.local object` errors because `knitr` uses "sub-dir" as root dir when knitting.

Currently my workaround is to use a second R-project in "sub-dir" to ensure that both knitting and running all chunks works with the same relativ paths (and that my folder structure does not get messy).

I wonder what I'm doing wrong here so that `here()` is not adjusting paths correctly in my case. I initially expected that `here()` is setting the working directory to the project root when knitting. Did I get this wrong? :sweat_smile:

**Comment by krlmlr** [comment]
Thanks. Could you please point me to your project, or attach an archive?

**Comment by pat-s** [comment]
In this example "Run All" chunks works. Knitting does not.

When changing `here("spring-school-hsdar/data")` to `here("data")`, i.e. making path relatives to the .Rmd file, knitting works but "Run All" does not work anymore (because paths to .Rproj files are wrong). 

I also played around with `knitr::opts_knit$set(root.dir = here())` but did not succeed. Even setting `knitr::opts_knit$set(root.dir = "/Users/pjs/Desktop/test")` (i.e. to the fixed path of the .Rproj dir) does not work. 

Yo will need `devtools::install_github("humburg/reportmd")` for the example. 

[Archive.zip](https://github.com/krlmlr/here/files/836428/Archive.zip)

**Comment by krlmlr** [comment]
Thanks. I'm seeing correct behavior with a simple document that is rendered with `rmarkdown::html_document`, but I can't get your example to run. I've installed the reportMD package, but knitting complains that a package "prompt" is missing, which I can't find.

Here's the minimal file I'm using in my tests:

`````
---
title: "Part 1: Data investigation & preprocessing"
author: "Patrick Schratz"
date: "`r format(Sys.time(), '%a %d %b %Y')`"
output:
  reportMD::multi_document:
    toc: true
    fig_caption: true
    highlight: dracula 
    css: R.css
    use_namespace: false
params:
  version: !r 
---

```{r loadPackages, include=FALSE, cache=FALSE}
## load additional packages in this chunk
library(here)
```

```{r}
here()
```
`````

Can you confirm that it works correctly with the following file:

`````
---
title: "Part 1: Data investigation & preprocessing"
author: "Patrick Schratz"
date: "`r format(Sys.time(), '%a %d %b %Y')`"
output:
  rmarkdown::html_document
params:
  version: !r 
---

```{r loadPackages, include=FALSE, cache=FALSE}
## load additional packages in this chunk
library(here)
```

```{r}
here()
```
`````
